# To limit automatically merging to certain packages or prod/dev, see:
# https://github.com/marketplace/actions/dependabot-auto-merge#configuration-file-syntax
#
# dependency_name   full name of dependency, or a regex string
# dependency_type   all, production, development
# update_type       all, security:*, semver:*

- match:
    dependency_type: all
    update_type: "semver:minor" # includes patch updates
