version: 2.1

orbs:
  terraform: circleci/terraform@3.0.1

jobs:
  publish:
    docker:
      - image: circleci/node:17@sha256:b2330f71df36d859dd822767ed7799bf67ea0a82efa451df6f121f52f7bd337d
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '95:3f:a9:02:0d:06:71:f9:5d:90:1e:a0:e5:e3:c3:25'
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run:
          name: Setup GitHub Token
          command: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
      - run: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - terraform/install:
          terraform_version: 0.13.5
      - run: npm run synth
      - run: npx semantic-release
      ## Let's update the package.json and then publish with a different name to npm registry.
      - run: echo $(jq '.name = "@pocket-tools/terraform-modules" | del(.publishConfig)' package.json) > package.json
      - run:
          name: Setup NPM Token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run: '(test -f .version && npm publish --access=public) || echo .version does not exist, no release was made, skipping npm registry publish'

workflows:
  all:
    jobs:
      - publish:
          context: pocket
          name: Publish NPM package

