version: 2.1

orbs:
  terraform: circleci/terraform@3.2.1

commands:
  setup_dependencies:
    description: Install npm packages and terraform
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '95:3f:a9:02:0d:06:71:f9:5d:90:1e:a0:e5:e3:c3:25'
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run:
          name: Setup GitHub Token
          command: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
      - run: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - node_modules
      - terraform/install:
          terraform_version: 1.1.1
      - run: npm run synth

jobs:
  publish:
    docker:
      - image: cimg/node:18.16@sha256:ffc2e6089568307e961a09485b073c440019cf920f23648ae2b8f7be1d1b0129
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_dependencies
      - run:
          name: Setup NPM Token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run: npx semantic-release

  test:
    resource_class: large
    docker:
      - image: cimg/node:18.16@sha256:ffc2e6089568307e961a09485b073c440019cf920f23648ae2b8f7be1d1b0129
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_dependencies
      - run:
          name: Test constructs
          command: npm run test-ci
      - run:
          name: Validate terraform
          command: cd cdktf.out/stacks/acme-example && terraform init && terraform validate

workflows:
  all:
    jobs:
      - test:
          context: pocket
          name: Test

      - publish:
          context: pocket
          name: Publish NPM package
