version: 2.1

orbs:
  terraform: circleci/terraform@3.0.1

commands:
  setup_dependencies:
    description: Install npm packages and terraform
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '95:3f:a9:02:0d:06:71:f9:5d:90:1e:a0:e5:e3:c3:25'
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run:
          name: Setup GitHub Token
          command: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
      - run: npm ci
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - node_modules
      - terraform/install:
          terraform_version: 0.13.5
      - run: npm run synth

jobs:
  publish:
    docker:
      - image: circleci/node:16@sha256:1803e9ed7deec9456ad2609124b7333d40b2eec0cf34998ae766cbf90c9a3625
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_dependencies
      - run: npx semantic-release
      ## Let's update the package.json and then publish with a different name to npm registry.
      - run: echo $(jq '.name = "@pocket-tools/terraform-modules" | del(.publishConfig)' package.json) > package.json
      - run:
          name: Setup NPM Token
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - run: '(test -f .version && npm publish --access=public) || echo .version does not exist, no release was made, skipping npm registry publish'

  test:
    resource_class: large
    docker:
      - image: circleci/node:16@sha256:1803e9ed7deec9456ad2609124b7333d40b2eec0cf34998ae766cbf90c9a3625
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_dependencies
      - run:
          name: Test constructs
          command: npm run test-ci
      - run:
          name: Validate terraform
          command: cd cdktf.out/stacks/acme-example && terraform init && terraform validate

workflows:
  all:
    jobs:
      - test:
          context: pocket
          name: Test

      - publish:
          context: pocket
          name: Publish NPM package

