name: Build NPM Package

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.0
          terraform_wrapper: false
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14.x'
      - run: npm install
      - run: npm run get
      - run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
