name: GitHub Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pocket'
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      - run: npm install
      - run: npm run get
      - run: npm run build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          # We use a personal access token from pocket-ci because secrets.GITHUB_TOKEN does not have necessary permissions
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
