name: Node.js NPM Package

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@pocket-tools'
      - run: npm install
      - run: npm run get
      - run: npm run build
      - run: npm run test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
